apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bq1jxpmya-go
  janus-idp.io/tekton: bq1jxpmya-go
  backstage.io/kubernetes-id: bq1jxpmya-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bq1jxpmya-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
