apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bq1jxpmya-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bq1jxpmya-go 
  name: bq1jxpmya-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bq1jxpmya-go 
